### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by marco4mp** [flathub/org.kde.koko#19]
Hello.

**Problem**
When opening Koko the icon is not shown in the panel and application launcher. 
I found two different behaviors depending on the session started (wayland vs xorg).

**Example**

- Wayland Session
![Koko wayland](https://user-images.githubusercontent.com/52709674/207959516-6bbc9e89-0f40-4cc0-a902-89aa8b16a705.png)

- X11 Session
![Koko xorg](https://user-images.githubusercontent.com/52709674/207959635-9ab3bb78-8b3f-446f-878f-9b30fa123e91.png)

**System**
Fedora 37 Kinoite
Plasma 5.26.4
Spanish language

**Comment by espidev** [comment]
Are you on X11?

**Comment by marco4mp** [comment]
@espidev Hi!, I have updated the information to be more precise.

**Comment by espidev** [comment]
Should be fixed as of latest update

**Comment by espidev** [comment]
https://github.com/flathub/org.kde.koko/pull/20
